### PR TITLE
spectator v5 endpoints update

### PR DESCRIPTION
**Pull request by PascalVorwerk**
@OllieJennings Hi, i have been working on a discord bot involving a few riot API calls like the spectator one. Your package has been of much help so i would like to help with implementing the v5 of the spectator api. 

I couldn't find any other points in the rate limiter that need changing, as the API endpoints did not change much and the DTO typings are in the riot-api package. I will try to update whatever needs updating on that package aswell!

### CODE REVIEW

**Comment by PascalVorwerk** [comment]
Its impossible for me to get the tests working, apart from simply disabling them without being able to access the Circle CI environment variables. I dont want to push anything like my API key to the repo. This will probably be easiest for you to fix.

**Comment by OllieJennings** [comment]
@PascalVorwerk awesome, thanks for this! l will be able to get the pipeline running so it should be good, let me trigger a run tomorrow and get this merged in!

**Comment by PascalVorwerk** [comment]
Cool, once i have time (probably the day after tomorrow) i will try to also get the riot-api package working with the new DTO's that they have. I believe there weren't any huge changes, just a few.

**Comment by PascalVorwerk** [comment]
Hey man! Did you have a chance yet to start a run?

**Comment by OllieJennings** [comment]
@PascalVorwerk really sorry, end up falling ill, but this shall be pushed out tomorrow!

**Comment by PascalVorwerk** [comment]
No worries, hope you feel better. I believe the API status has been on 'down' for the past week anyways.

**Pull request merged**
